library(emuR, warn.conflicts = FALSE)
dbPath = file.path(Sys.getenv("PROJECT_PATH"), "Data", "VISP_emuDB")
VISPDB = load_emuDB(dbPath)
bndls = list_bundles(VISPDB)
write_bundleList(VISPDB, name = "user.user", bndls)
