library(emuR, warn.conflicts = FALSE)
dbPath = file.path(Sys.getenv("PROJECT_PATH"), "Data", "VISP_emuDB")
VISPDB = load_emuDB(dbPath)
bundles <- list_bundles(VISPDB)
bundlesJson <- jsonlite::toJSON(bundles)
print(bundlesJson)
