library(emuR, warn.conflicts = FALSE)
dbPath = file.path(Sys.getenv("PROJECT_PATH"), "Data", "VISP_emuDB")
VISPDB = load_emuDB(dbPath)
sessions <- list_sessions(VISPDB)
sessionsJson <- jsonlite::toJSON(sessions)
print(sessionsJson)
