library(emuR, warn.conflicts = FALSE)
#library(reindeer)
dbPath = file.path(Sys.getenv("PROJECT_PATH"), "Data", "VISP_emuDB")
VISPDB = load_emuDB(dbPath)
remove_linkDefinition(VISPDB, superlevelName = Sys.getenv("ANNOT_LEVEL_LINK_SUPER"), sublevelName = Sys.getenv("ANNOT_LEVEL_LINK_SUB"))
